config/routes.rb
Rails.application.routes.draw do

  root to: 'home_pages#index'

  resources :home_pages, only: [:index]
  resources :charges

end

app/models/home_page.rb
class HomePage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = params[:amount]

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Zeta Psi Customer',
      :currency    => 'cad'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_action :set_home_page, only: [:show, :edit, :update, :destroy]

  # GET /home_pages
  # GET /home_pages.json
  def index
    @home_pages = HomePage.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency(@amount.to_i / 100) %></strong>!</h2>
<h2>You will receive an email with your receipt shortly.</h2>
<%= link_to 'Back...', root_url, style: 'text-decoration: none;' %>

app/views/home_pages/index.html.erb
<div class="jumbotron">
  <div class="row">
    <%= image_tag('ttheta.jpg', size: '115x150', style: 'display: table; margin: 0 auto; border-radius: 5px;') %>
  </div>
  <div class="row">
    <h2 style="text-align: center">Zeta Psi Presents...</h2>
    <h4 style="text-align: center">Tau Theta's 13th Annual Anniversary Banquet</h4>
  </div>
  <div class="row">
    <p>March 3, 2018</p>
    <a href="#" class="location" style="text-decoration: none;">Tosca Banquet Hall</a>
    <br>
    <a href="#" class="location" style="text-decoration: none;">Oshawa, ON</a>
  </div>
</div>

<div class="jumbotron" style="font-size: 18px">
  <div class="row">
    The Brothers of the Zeta Psi Fraternity Tau Theta Chapter invite you to an evening of celebration to
    commemorate our 13 year anniversary.  The night will be filled with great company, dinner, drinks and dancing.
    Cocktails start at 6pm and dinner will be served at 7pm.  There will also be a silent auction running throughout
    the evening.
  </div>
  <div class="row" style="margin-top: 20px;">
    Active and Elder tickets will be $65 and $75 respectively; We look forward to hosting
    you this year and celebrating 13 years of brotherhood at Tau Theta.
  </div>
  <div class="row" style="margin-top: 20px;">
    Tau Kappa Phi,
  </div>
  <div class="row">
    - The Banquet Staff
  </div>
  <div class="row">
    <h4><small style="color: black;">Dress Code: Black Tie Preferred</small></h4>
  </div>
  <div class="row" style="color: black; margin-top: 20px;">
    If you have any questions please contact <a href="mailto:gamma1847@gmail.com">your banquet commitee.</a>
  </div>
</div>

<div id="map" class="jumbotron" style="height: 400px; width: 100%;">
</div>

<div class="jumbotron">
  <h2>Purchase Your Tickets</h2>
  <h4><small style="color: white;">*Active ticket prices will go up after March 1st.</small></h4>
  <div class="row">
    <span>
      <%= form_tag charges_path do %>
        <%= hidden_field_tag :amount, 6500 %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Active Ticket"
                data-amount="6500"
                data-label="Active Ticket"
                data-locale="auto"></script>
      <% end %>
    </span>
    <span>
      <%= form_tag charges_path do %>
        <%= hidden_field_tag :amount, 13000 %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Active + Guest Ticket"
                data-amount="13000"
                data-label="Active + Guest Ticket"
                data-locale="auto"></script>
      <% end %>
    </span>
    <span>
      <%= form_tag charges_path do %>
        <%= hidden_field_tag :amount, 7500 %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Elder Ticket"
                data-amount="7500"
                data-label="Elder Ticket"
                data-locale="auto"></script>
      <% end %>
    </span>
  </div>
  <div class="row">
    <span>
      <%= form_tag charges_path do %>
        <%= hidden_field_tag :amount, 15000 %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Elder + Guest Ticket"
                data-amount="15000"
                data-label="Elder + Guest Ticket"
                data-locale="auto"></script>
      <% end %>
    </span>
    <span>
      <%= form_tag charges_path do %>
        <%= hidden_field_tag :amount, 22500 %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Elder Ticket + Dues"
                data-amount="22500"
                data-label="Elder Ticket + Dues"
                data-locale="auto"></script>
      <% end %>
    </span>
  </div>
</div>

<script>
  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 17,
      center: {lat: 43.8742923, lng: -78.8886865},
      scrollwheel: false
    });
    var geocoder = new google.maps.Geocoder();

    geocodeAddress(geocoder, map);
  }

  function geocodeAddress(geocoder, resultsMap) {
    var address = 'Tosca Banquet Hall';
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === 'OK') {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location,
          icon: "<%= ActionController::Base.helpers.asset_path('map-marker-icon.png') %>"
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDU3Y1dluzVy2p_X48j8GRPbCzv1KFftxQ&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BanquetV2</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- <div class="container"> -->
    <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-inverse navbar-static-top navbar-gold">
        <div class="container-fluid" style="background-color: black;">
          <div class="navbar-header">
            <%= image_tag('ztrident.jpg', size: '75x50', style: 'float: left;') %>
            <ul class="nav navbar-nav">
              <li class="active"><a href="#" style="color: gold;">Tau Theta Annual Banquet</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    <div class="container">
      <%= yield %>
    </div>
  <!-- </div> -->

</body>
</html>